export const fillwordsObjects = [
    // line 1
    { line: 1, column: 1, symbol: 'м' },
    { line: 1, column: 2, symbol: 'о' },
    { line: 1, column: 3, symbol: 'д' },
    { line: 1, column: 4, symbol: 'у' },
    { line: 1, column: 5, symbol: 'л' },
    { line: 1, column: 6, symbol: 'ь' },
    { line: 1, column: 7, symbol: 'р' },
    { line: 1, column: 8, symbol: 'е' },
    { line: 1, column: 9, symbol: 'д' },
    { line: 1, column: 10, symbol: 'е' },

    // line 2
    { line: 2, column: 1, symbol: 'р' },
    { line: 2, column: 2, symbol: 'е' },
    { line: 2, column: 3, symbol: 'п' },
    { line: 2, column: 4, symbol: 'о' },
    { line: 2, column: 5, symbol: 'з' },
    { line: 2, column: 6, symbol: 'и' },
    { line: 2, column: 7, symbol: 'т' },
    { line: 2, column: 8, symbol: 'п' },
    { line: 2, column: 9, symbol: 'о' },
    { line: 2, column: 10, symbol: 'д' },

    // line 3
    { line: 3, column: 1, symbol: 'в' },
    { line: 3, column: 2, symbol: 'і' },
    { line: 3, column: 3, symbol: 'р' },
    { line: 3, column: 4, symbol: 'у' },
    { line: 3, column: 5, symbol: 'с' },
    { line: 3, column: 6, symbol: 'м' },
    { line: 3, column: 7, symbol: 'о' },
    { line: 3, column: 8, symbol: 'в' },
    { line: 3, column: 9, symbol: 'р' },
    { line: 3, column: 10, symbol: 'л' },

    // line 4
    { line: 4, column: 1, symbol: 'с' },
    { line: 4, column: 2, symbol: 'к' },
    { line: 4, column: 3, symbol: 'р' },
    { line: 4, column: 4, symbol: 'а' },
    { line: 4, column: 5, symbol: 'м' },
    { line: 4, column: 6, symbol: 'і' },
    { line: 4, column: 7, symbol: 'р' },
    { line: 4, column: 8, symbol: 'е' },
    { line: 4, column: 9, symbol: 'т' },
    { line: 4, column: 10, symbol: 'а' },

    // line 5
    { line: 5, column: 1, symbol: 'н' },
    { line: 5, column: 2, symbol: 'т' },
    { line: 5, column: 3, symbol: 'е' },
    { line: 5, column: 4, symbol: 'г' },
    { line: 5, column: 5, symbol: 'р' },
    { line: 5, column: 6, symbol: 'т' },
    { line: 5, column: 7, symbol: 'і' },
    { line: 5, column: 8, symbol: 'р' },
    { line: 5, column: 9, symbol: 'с' },
    { line: 5, column: 10, symbol: 'й' },

    // line 6
    { line: 6, column: 1, symbol: 'і' },
    { line: 6, column: 2, symbol: 'я' },
    { line: 6, column: 3, symbol: 'і' },
    { line: 6, column: 4, symbol: 'ц' },
    { line: 6, column: 5, symbol: 'а' },
    { line: 6, column: 6, symbol: 'а' },
    { line: 6, column: 7, symbol: 'й' },
    { line: 6, column: 8, symbol: 'с' },
    { line: 6, column: 9, symbol: 'е' },
    { line: 6, column: 10, symbol: 'н' },

    // line 7
    { line: 7, column: 1, symbol: 'а' },
    { line: 7, column: 2, symbol: 'т' },
    { line: 7, column: 3, symbol: 'е' },
    { line: 7, column: 4, symbol: 'с' },
    { line: 7, column: 5, symbol: 'т' },
    { line: 7, column: 6, symbol: 'п' },
    { line: 7, column: 7, symbol: 'я' },
    { line: 7, column: 8, symbol: 'і' },
    { line: 7, column: 9, symbol: 'р' },
    { line: 7, column: 10, symbol: 'б' },

    // line 8
    { line: 8, column: 1, symbol: 'р' },
    { line: 8, column: 2, symbol: 'л' },
    { line: 8, column: 3, symbol: 'а' },
    { line: 8, column: 4, symbol: 'в' },
    { line: 8, column: 5, symbol: 'у' },
    { line: 8, column: 6, symbol: 'б' },
    { line: 8, column: 7, symbol: 'е' },
    { line: 8, column: 8, symbol: 'к' },
    { line: 8, column: 9, symbol: 'в' },
    { line: 8, column: 10, symbol: 'і' },

    // line 9
    { line: 9, column: 1, symbol: 'х' },
    { line: 9, column: 2, symbol: 'ь' },
    { line: 9, column: 3, symbol: 'н' },
    { line: 9, column: 4, symbol: 'и' },
    { line: 9, column: 5, symbol: 'к' },
    { line: 9, column: 6, symbol: 'р' },
    { line: 9, column: 7, symbol: 'а' },
    { line: 9, column: 8, symbol: 'л' },
    { line: 9, column: 9, symbol: 'е' },
    { line: 9, column: 10, symbol: 'л' },

    // line 10
    { line: 10, column: 1, symbol: 'і' },
    { line: 10, column: 2, symbol: 'т' },
    { line: 10, column: 3, symbol: 'е' },
    { line: 10, column: 4, symbol: 'к' },
    { line: 10, column: 5, symbol: 'т' },
    { line: 10, column: 6, symbol: 'у' },
    { line: 10, column: 7, symbol: 'г' },
    { line: 10, column: 8, symbol: 'о' },
    { line: 10, column: 9, symbol: 'р' },
    { line: 10, column: 10, symbol: 'д' },
]