export const subjectsArray = [
    // main left column
    {
        id: '№',
        posX: 485,
        posY: 165,
        firstColumnName: 'ДИСЦИПЛІНА',
        secondColumnName: 'ГОДИНИ',
        color: '#04975f'
    },
    {
        mainSubjectId: 1,
        subjectName: 'Вступ до комп\'ютерних наук',
        posX: 490,
        posY: 210,
        hours: 105,
        min: 75,
        max: 135,
        minusButton: { posX: 790, posY: 200, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 900, posY: 200, name: 'btn-grey', symbol: '+'  },
    },
    {
        mainSubjectId: 2,
        subjectName: 'Комп\'ютерна графіка',
        posX: 490,
        posY: 260,
        hours: 120,
        min: 90,
        max: 150,
        minusButton: { posX: 790, posY: 250, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 900, posY: 250, name: 'btn-white', symbol: '+' },
    },
    {
        mainSubjectId: 3,
        subjectName: 'Алгоритмізація і програмування',
        posX: 490,
        posY: 310,
        hours: 258,
        min: 238,
        max: 288,
        minusButton: { posX: 790, posY: 300, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 900, posY: 300, name: 'btn-grey', symbol: '+' },
    },
    {
        mainSubjectId: 4,
        subjectName: 'Комп\'ютерна схемотехніка \nта архітектура комп\'ютерів',
        posX: 490,
        posY: 355,
        hours: 105,
        min: 135,
        max: 75,
        minusButton: { posX: 790, posY: 345, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 900, posY: 345, name: 'btn-white', symbol: '+' },
    },
    {
        mainSubjectId: 5,
        subjectName: 'Операційні системи та \nсистемне програмування',
        posX: 490,
        posY: 405,
        hours: 210,
        min: 80,
        max: 240,
        minusButton: { posX: 790, posY: 395, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 900, posY: 395, name: 'btn-grey', symbol: '+' },
    },
    {
        mainSubjectId: 6,
        subjectName: 'Комп\'ютерні мережі',
        posX: 490,
        posY: 455,
        hours: 225,
        min: 95,
        max: 255,
        minusButton: { posX: 790, posY: 445, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 900, posY: 445, name: 'btn-white', symbol: '+'},
    },
    {
        mainSubjectId: 7,
        subjectName: 'Організація баз даних і знань',
        posX: 490,
        posY: 505,
        hours: 240,
        min: 210,
        max: 270,
        minusButton: { posX: 790, posY: 495, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 900, posY: 495, name: 'btn-grey', symbol: '+' },
    },
    {
        mainSubjectId: 8,
        subjectName: 'Об\'єктно-орієнтоване \nпрограмування',
        posX: 490,
        posY: 555,
        hours: 120,
        min: 90,
        max: 150,
        minusButton: { posX: 790, posY: 545, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 900, posY: 545, name: 'btn-white', symbol: '+' },
    },

    // main right column
    {
        id: '№',
        posX: 980,
        posY: 165,
        firstColumnName: 'ДИСЦИПЛІНА',
        secondColumnName: 'ВИБІР',
        color: '#04975f'
    },
    {
        mainSubjectId: 9,
        subjectName: 'Моделювання систем',
        posX: 975,
        posY: 210,
        hours: 135,
        min: 10,
        max: 165,
        minusButton: { posX: 1280, posY: 200, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 1395, posY: 200, name: 'btn-grey', symbol: '+' },
    },
    {
        mainSubjectId: 10,
        subjectName: 'Проектування інформаційних \nсистем',
        posX: 975,
        posY: 250,
        hours: 120,
        min: 90,
        max: 150,
        minusButton: { posX: 1280, posY: 250, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 1395, posY: 250, name: 'btn-white', symbol: '+' },
    },
    {
        mainSubjectId: 11,
        subjectName: 'Розподілені інформаційно-\nаналітичні системи',
        posX: 975,
        posY: 310,
        hours: 120,
        min: 90,
        max: 150,
        minusButton: { posX: 1280, posY: 300, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 1395, posY: 300, name: 'btn-grey', symbol: '+' },
    },
    {
        mainSubjectId: 12,
        subjectName: 'Системний аналіз',
        posX: 975,
        posY: 355,
        hours: 120,
        min: 90,
        max: 150,
        minusButton: { posX: 1280, posY: 345, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 1395, posY: 345, name: 'btn-white', symbol: '+' },
    },
    {
        mainSubjectId: 13,
        subjectName: 'Технології захисту інформації',
        posX: 975,
        posY: 405,
        hours: 120,
        min: 90,
        max: 150,
        minusButton: { posX: 1280, posY: 395, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 1395, posY: 395, name: 'btn-grey', symbol: '+' },
    },
    {
        mainSubjectId: 14,
        subjectName: 'Технології розподілених \nсистем та паралельних обчислень',
        posX: 975,
        posY: 455,
        hours: 120,
        min: 90,
        max: 150,
        minusButton: { posX: 1280, posY: 445, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 1395, posY: 445, name: 'btn-white', symbol: '+' },
    },
    {
        mainSubjectId: 15,
        subjectName: 'Технології створення \nпрограмних продуктів',
        posX: 975,
        posY: 505,
        hours: 105,
        min: 75,
        max: 135,
        minusButton: { posX: 1280, posY: 495, name: 'btn-grey', symbol: '-' },
        plusButton: { posX: 1395, posY: 495, name: 'btn-grey', symbol: '+' },
    },
    {
        mainSubjectId: 16,
        subjectName: 'Управління ІТ-проектами',
        posX: 975,
        posY: 555,
        hours: 105,
        min: 75,
        max: 135,
        minusButton: { posX: 1280, posY: 545, name: 'btn-white', symbol: '-' },
        plusButton: { posX: 1395, posY: 545, name: 'btn-white', symbol: '+' },
    },

    // other left column
    {
        id: '№',
        posX: 485,
        posY: 646,
        firstColumnName: 'ДИСЦИПЛІНА',
        secondColumnName: 'ВИБІР',
        color: '#04975f'
    },
    {
        optionalSubjectId: 1,
        posX: 490,
        posY: 696,
        subjectName: 'Методи і системи штучного \nінтелекту',
        checkbox: { posX: 845, posY: 686, name: 'btn-grey' },
    },
    {
        optionalSubjectId: 2,
        subjectName: 'Інтелектуальний аналіз даних',
        posX: 490,
        posY: 746,
        checkbox: { posX: 845, posY: 736, name: 'btn-white' },
    },
    {
        optionalSubjectId: 3,
        subjectName: 'Інформаційні системи \nуправління підприємством',
        posX: 490,
        posY: 796,
        checkbox: { posX: 845, posY: 786, name: 'btn-grey' },
    },
    {
        optionalSubjectId: 4,
        subjectName: 'Статистичні методи \nобробки інформації',
        posX: 490,
        posY: 846,
        checkbox: { posX: 845, posY: 836, name: 'btn-white' },
    },


    // other right column
    {
        id: '№',
        posX: 980,
        posY: 646,
        firstColumnName: 'ДИСЦИПЛІНА',
        secondColumnName: 'ВИБІР',
        color: '#04975f'
    },
    {
        optionalSubjectId: 5,
        subjectName: 'Тестування та верифікація \nпрограмного забезпечення',
        posX: 980,
        posY: 696,
        checkbox: { posX: 1335, posY: 686, name: 'btn-grey' },
    },
    {
        optionalSubjectId: 6,
        subjectName: 'Технології розробки \nкросплатформенних додатків',
        posX: 980,
        posY: 746,
        checkbox: { posX: 1335, posY: 736, name: 'btn-white', },
    },
    {
        optionalSubjectId: 7,
        subjectName: 'Веб-дизайн та сучасні \nВеб-технології',
        posX: 980,
        posY: 796,
        checkbox: { posX: 1335, posY: 786, name: 'btn-grey', },
    },
];